# name: Deploy to Heroku

# on:
#   push:
#     branches:
#       - main

# jobs:
#   install:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x]
#     steps:
#       - uses: actions/checkout@v2

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'

#       - name: Install dependencies with clean install
#         run: npm ci

#   lint:
#     runs-on: ubuntu-latest
#     needs: install
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x]
#     steps:
#       - uses: actions/checkout@v2

#       - name: Use cached dependencies ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
          
#       - run: npm install
#       - run: npm run lint
#       - run: npm run lint:css

#   test: 
#     runs-on: ubuntu-latest
#     needs: install
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x]
#     steps:
#       - uses: actions/checkout@v2

#       - name: Use cached dependencies ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'

#       - run: npm install
#       - run: npm run test

#   build:
#     runs-on: ubuntu-latest
#     needs: install
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x]
#     steps:
#       - uses: actions/checkout@v2

#       - name: Use cached dependencies ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'

#       - run: npm install
#       - run: npm run build

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - uses: actions/checkout@v2
#       # Custom action to deploy to heroku
#       - uses: akhileshns/heroku-deploy@v3.12.12
#         with:
#           # Confiured secret in Github secrets with the Heroku API key
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "torn-pages"
#           heroku_email: "lawrence.good55@gmail.com"