name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      # Install dependencies
      - run: npm install
      # Deploy to Netlify
      - name: Deploy to Netlify
      # Custom action to deploy to heroku
        uses: netlify/actions/cli@master
        env: 
        with:
          args: deploy --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'