name: Test

# Controls when the workflow will run
on:
  push:
    branches: 
      - '**'
      - '!main'
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# They run in parallel unless the "need" property is specified
jobs:
  # This job performs the npm clean install and caches the dependencies.
  # The subsequent jobs will have to include the setup-node step prior
  # to the npm install so that it will use the cache
  install:
    runs-on: ubuntu-latest
    strategy:
      # Matrix allows the job to be run once with each different variables
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies with clean install
        run: npm ci

  test: 
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use cached dependencies ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm run test